name: DeployApplication
on:
  push:
    banches:
      - master
jobs:
  build:

      runs-on: ubuntu-latest


      steps:
        - uses: actions/checkout@v1
        - name: Install Packages
          run: npm install
        - name: Deploy to GH Pages
          run: npm run deploy
