name: DeployApplication
on:
  push:
    banches:
      - master
jobs:
  build:

      runs-on: ubuntu-latest
      strategy: 
        matrix:
          node-version: [8.x, 10.x, 12.x]

      steps:
        - uses: actions/checkout@v1
        - name: Set up node version ${{ matrix.node-version }}
          uses: action/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install Packages
          run: npm install
        - name: Deploy to GH Pages
          run: npm run deploy
